version: "3.9"
services:
  sb-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=dev_sb_db_user
      - POSTGRES_DB=dev_sb_db
      - POSTGRES_PASSWORD=dev_sb_db_password
    ports:
      - "5432:5432"